# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

max_jobs: 1

shallow_clone: true

init:
  - git config --global core.autocrlf true

image:
  - Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install -g github:apache/cordova-paramedic
  - npm install -g cordova

build: off

test_script:
  - cordova-paramedic --config pr\windows-10-store --plugin . --justBuild
